import type { AdminCollectionConfig } from '@/types/admin'

export const adminCollections: AdminCollectionConfig[] = [
  {
    key: 'city',
    label: 'Byer',
    pendingType: 'city',
    description: 'Godkend afventende byforslag, og vedligehold bysamlingen.',
    emptyRecord: {
      name: '',
      tagLine: '',
      description: '',
      heroImage: '',
      commune: '',
      region: '',
      country: 'Danmark',
      gpsPosition: '',
      population: 0,
      visitorCenter: '',
    },
    fields: [
      { key: 'name', label: 'Navn', type: 'text', required: true },
      { key: 'tagLine', label: 'Tagline', type: 'text', required: true },
      { key: 'description', label: 'Beskrivelse', type: 'textarea', required: true },
      { key: 'heroImage', label: 'Hero-billede', type: 'image', required: true },
      { key: 'commune', label: 'Kommune', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'country', label: 'Land', type: 'text', required: true },
      { key: 'population', label: 'Indbyggertal', type: 'number', required: true },
      { key: 'visitorCenter', label: 'Besøgscenter', type: 'text', required: true },
    ],
  },
  {
    key: 'attractions',
    label: 'Attraktioner',
    pendingType: 'attraction',
    description: 'Godkend afventende attraktionsforslag, og vedligehold attraktioner.',
    emptyRecord: {
      name: '',
      description: '',
      heroImage: '',
      imageArray: [],
      price: 0,
      link: '',
      address: '',
      city: '',
      gpsPosition: '',
      slugArray: [],
      openingHours: [],
    },
    fields: [
      { key: 'name', label: 'Navn', type: 'text', required: true },
      { key: 'description', label: 'Beskrivelse', type: 'textarea', required: true },
      { key: 'heroImage', label: 'Hero-billede', type: 'image', required: true },
      { key: 'imageArray', label: 'Billeder', type: 'image-list' },
      { key: 'price', label: 'Pris', type: 'number', required: true },
      { key: 'link', label: 'Link', type: 'text', required: true },
      { key: 'address', label: 'Adresse', type: 'text' },
      { key: 'city', label: 'By', type: 'text' },
      { key: 'slugArray', label: 'Kategorier', type: 'slug-picker' },
      { key: 'openingHours', label: 'Åbningstider', type: 'tags' },
    ],
  },
  {
    key: 'events',
    label: 'Events',
    pendingType: 'event',
    description: 'Godkend afventende eventforslag, og vedligehold events.',
    emptyRecord: {
      name: '',
      description: '',
      heroImage: '',
      imageArray: [],
      price: 0,
      link: '',
      address: '',
      city: '',
      gpsPosition: '',
      slugArray: [],
      isAnnual: false,
      startDate: '',
      endDate: '',
      openingHours: [],
    },
    fields: [
      { key: 'name', label: 'Navn', type: 'text', required: true },
      { key: 'description', label: 'Beskrivelse', type: 'textarea', required: true },
      { key: 'heroImage', label: 'Hero-billede', type: 'image', required: true },
      { key: 'imageArray', label: 'Billeder', type: 'image-list' },
      { key: 'price', label: 'Pris', type: 'number', required: true },
      { key: 'link', label: 'Link', type: 'text', required: true },
      { key: 'address', label: 'Adresse', type: 'text' },
      { key: 'city', label: 'By', type: 'text' },
      { key: 'slugArray', label: 'Kategorier', type: 'slug-picker' },
      { key: 'isAnnual', label: 'Årligt event', type: 'checkbox' },
      { key: 'startDate', label: 'Startdato', type: 'date', required: true },
      { key: 'endDate', label: 'Slutdato', type: 'date', required: true },
      { key: 'openingHours', label: 'Åbningstider', type: 'tags' },
    ],
  },
]
