"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const attractionController_1 = require("../controllers/attractionController");
const contactTicketController_1 = require("../controllers/contactTicketController");
const contentSuggestionController_1 = require("../controllers/contentSuggestionController");
const cityController_1 = require("../controllers/cityController");
const eventController_1 = require("../controllers/eventController");
const reviewController_1 = require("../controllers/reviewController");
const reviewReportController_1 = require("../controllers/reviewReportController");
const rateLimit_1 = require("../middleware/rateLimit");
const requireAdmin_1 = require("../middleware/requireAdmin");
const requirePermission_1 = require("../middleware/requirePermission");
const verifyUserToken_1 = require("../middleware/verifyUserToken");
const router = (0, express_1.Router)();
router.get("/admin/suggestions", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, (0, requirePermission_1.requirePermission)("admin:access"), contentSuggestionController_1.getContentSuggestions);
router.post("/admin/suggestions/:id/approve", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, (0, requirePermission_1.requirePermission)("admin:access"), contentSuggestionController_1.approveContentSuggestion);
router.post("/admin/suggestions/:id/reject", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, (0, requirePermission_1.requirePermission)("admin:access"), contentSuggestionController_1.rejectContentSuggestion);
router.get("/admin/contact/tickets", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, contactTicketController_1.getAdminContactTickets);
router.patch("/admin/contact/tickets/:id/seen", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, contactTicketController_1.markContactTicketSeen);
router.patch("/admin/contact/tickets/:id/start", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, contactTicketController_1.startContactTicketWork);
router.patch("/admin/contact/tickets/:id/complete", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, contactTicketController_1.completeContactTicket);
router.patch("/admin/contact/tickets/:id/reject", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, contactTicketController_1.rejectContactTicket);
router.patch("/admin/contact/tickets/:id/reopen", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, contactTicketController_1.reopenContactTicket);
router.get("/admin/city", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, cityController_1.getAllCities);
router.post("/admin/city", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, cityController_1.createCity);
router.put("/admin/city/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, cityController_1.updateCityById);
router.patch("/admin/city/:id/restore", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, cityController_1.restoreCityById);
router.delete("/admin/city/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, cityController_1.deleteCityById);
router.get("/admin/attractions", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, attractionController_1.getAllAttractions);
router.post("/admin/attractions", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, attractionController_1.createAttraction);
router.put("/admin/attractions/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, attractionController_1.updateAttractionById);
router.delete("/admin/attractions/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, attractionController_1.deleteAttractionById);
router.patch("/admin/attractions/:id/restore", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, attractionController_1.restoreAttractionById);
router.get("/admin/events", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, eventController_1.getAllEvents);
router.post("/admin/events", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, eventController_1.createEvent);
router.put("/admin/events/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, eventController_1.updateEventById);
router.patch("/admin/events/:id/restore", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, eventController_1.restoreEventById);
router.delete("/admin/events/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, eventController_1.deleteEventById);
router.get("/admin/reviews/reports", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, reviewReportController_1.getReportedReviews);
router.put("/admin/reviews/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, reviewController_1.updateReviewById);
router.patch("/admin/reviews/:id/resolve-report", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, reviewReportController_1.resolveReviewReport);
router.delete("/admin/reviews/:id", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, reviewController_1.deleteReviewById);
router.patch("/admin/reviews/:id/restore", verifyUserToken_1.verifyToken, requireAdmin_1.requireAdmin, rateLimit_1.adminMutationRateLimiter, reviewController_1.restoreReviewById);
exports.default = router;
//# sourceMappingURL=adminRoutes.js.map